apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy
  labels:
    service: reverseproxy
spec:
  replicas: 2
  selector:
    matchLabels:
      service: reverseproxy
  template:
    metadata:
      labels:
        service: reverseproxy
    spec:
      containers:
      - name: udagram-reverseproxy
        image: salmanetamo/udagram-reverseproxy
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        imagePullPolicy: Always          
        resources:
          requests:
            memory: "1024Mi"
            cpu: "250m"
          limits:
            memory: "8192Mi"
            cpu: "500m"
      restartPolicy: Always
